// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IrisDanded.Pulumi.Squadcast.Workflow.Inputs
{

    public sealed class ActionComponentAndImpactGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ID of the component
        /// </summary>
        [Input("componentId", required: true)]
        public Input<int> ComponentId { get; set; } = null!;

        /// <summary>
        /// The ID of the impact status
        /// </summary>
        [Input("impactStatusId", required: true)]
        public Input<int> ImpactStatusId { get; set; } = null!;

        public ActionComponentAndImpactGetArgs()
        {
        }
        public static new ActionComponentAndImpactGetArgs Empty => new ActionComponentAndImpactGetArgs();
    }
}
