# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = [
    'PageOwner',
    'PageThemeColor',
]

@pulumi.output_type
class PageOwner(dict):
    def __init__(__self__, *,
                 id: str,
                 type: str):
        """
        :param str id: Status page owner id.
        :param str type: Status page owner type Supported values are 'user' or 'squad'.
        """
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "type", type)

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        Status page owner id.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def type(self) -> str:
        """
        Status page owner type Supported values are 'user' or 'squad'.
        """
        return pulumi.get(self, "type")


@pulumi.output_type
class PageThemeColor(dict):
    def __init__(__self__, *,
                 primary: str,
                 secondary: str):
        """
        :param str primary: Primary color.
        :param str secondary: Secondary color.
        """
        pulumi.set(__self__, "primary", primary)
        pulumi.set(__self__, "secondary", secondary)

    @property
    @pulumi.getter
    def primary(self) -> str:
        """
        Primary color.
        """
        return pulumi.get(self, "primary")

    @property
    @pulumi.getter
    def secondary(self) -> str:
        """
        Secondary color.
        """
        return pulumi.get(self, "secondary")


