// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IrisDanded.Pulumi.Squadcast.RoutingRule.Inputs
{

    public sealed class RuleV2BasicExpressionGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// left hand side dropdown value
        /// </summary>
        [Input("lhs", required: true)]
        public Input<string> Lhs { get; set; } = null!;

        /// <summary>
        /// right hand side value
        /// </summary>
        [Input("rhs", required: true)]
        public Input<string> Rhs { get; set; } = null!;

        public RuleV2BasicExpressionGetArgs()
        {
        }
        public static new RuleV2BasicExpressionGetArgs Empty => new RuleV2BasicExpressionGetArgs();
    }
}
