// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IrisDanded.Pulumi.Squadcast.Outputs
{

    [OutputType]
    public sealed class GetTeamRoleResult
    {
        public readonly ImmutableArray<string> Abilities;
        /// <summary>
        /// Role is default.
        /// </summary>
        public readonly bool Default;
        /// <summary>
        /// Role id.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Role name.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private GetTeamRoleResult(
            ImmutableArray<string> abilities,

            bool @default,

            string id,

            string name)
        {
            Abilities = abilities;
            Default = @default;
            Id = id;
            Name = name;
        }
    }
}
