// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IrisDanded.Pulumi.Squadcast.Outputs
{

    [OutputType]
    public sealed class ServiceMaintainer
    {
        /// <summary>
        /// The id of the maintainer.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The type of the maintainer. Supported values are 'user' or 'squad'.
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private ServiceMaintainer(
            string id,

            string type)
        {
            Id = id;
            Type = type;
        }
    }
}
