// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IrisDanded.Pulumi.Squadcast.StatusPage
{
    /// <summary>
    /// Status page component defines a component that represents a specific element within a status page. This resource enables you to configure various attributes of the component, and optionally associate it with a group on the status page.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Squadcast = IrisDanded.Pulumi.Squadcast;
    /// using Squadcast = Pulumi.Squadcast;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var team = Squadcast.GetTeam.Invoke(new()
    ///     {
    ///         Name = "Default Team",
    ///     });
    /// 
    ///     var user = Squadcast.GetUser.Invoke(new()
    ///     {
    ///         Email = "john@example.com",
    ///     });
    /// 
    ///     var testStatusPage = new Squadcast.Status.Page("testStatusPage", new()
    ///     {
    ///         TeamId = team.Apply(getTeamResult =&gt; getTeamResult.Id),
    ///         Description = "Status Page description",
    ///         IsPublic = true,
    ///         DomainName = "test-statuspage",
    ///         Timezone = "Asia/Kolkata",
    ///         ContactEmail = "example@test.com",
    ///         ThemeColor = new Squadcast.Status.Inputs.PageThemeColorArgs
    ///         {
    ///             Primary = "#000000",
    ///             Secondary = "#dddddd",
    ///         },
    ///         Owner = new Squadcast.Status.Inputs.PageOwnerArgs
    ///         {
    ///             Type = "user",
    ///             Id = user.Apply(getUserResult =&gt; getUserResult.Id),
    ///         },
    ///     });
    /// 
    ///     var exampleGroup = new Squadcast.StatusPage.PageGroup("exampleGroup", new()
    ///     {
    ///         StatusPageId = testStatusPage.Id,
    ///     });
    /// 
    ///     var exampleComponent = new Squadcast.StatusPage.PageComponent("exampleComponent", new()
    ///     {
    ///         StatusPageId = testStatusPage.Id,
    ///         Description = "Component 1 description",
    ///         GroupId = exampleGroup.Id,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// statusPageID:componentID
    /// 
    /// ```sh
    /// $ pulumi import squadcast:StatusPage/pageComponent:PageComponent test_component 300:573
    /// ```
    /// </summary>
    [SquadcastResourceType("squadcast:StatusPage/pageComponent:PageComponent")]
    public partial class PageComponent : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Description of the status page component.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Id of the group to which this component belongs to.
        /// </summary>
        [Output("groupId")]
        public Output<string?> GroupId { get; private set; } = null!;

        /// <summary>
        /// Name of the status page component.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Id of the status page to which this component belongs to.
        /// </summary>
        [Output("statusPageId")]
        public Output<string> StatusPageId { get; private set; } = null!;


        /// <summary>
        /// Create a PageComponent resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PageComponent(string name, PageComponentArgs args, CustomResourceOptions? options = null)
            : base("squadcast:StatusPage/pageComponent:PageComponent", name, args ?? new PageComponentArgs(), MakeResourceOptions(options, ""))
        {
        }

        private PageComponent(string name, Input<string> id, PageComponentState? state = null, CustomResourceOptions? options = null)
            : base("squadcast:StatusPage/pageComponent:PageComponent", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/IrisDande/pulumi-squadcast",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PageComponent resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PageComponent Get(string name, Input<string> id, PageComponentState? state = null, CustomResourceOptions? options = null)
        {
            return new PageComponent(name, id, state, options);
        }
    }

    public sealed class PageComponentArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Description of the status page component.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Id of the group to which this component belongs to.
        /// </summary>
        [Input("groupId")]
        public Input<string>? GroupId { get; set; }

        /// <summary>
        /// Name of the status page component.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Id of the status page to which this component belongs to.
        /// </summary>
        [Input("statusPageId", required: true)]
        public Input<string> StatusPageId { get; set; } = null!;

        public PageComponentArgs()
        {
        }
        public static new PageComponentArgs Empty => new PageComponentArgs();
    }

    public sealed class PageComponentState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Description of the status page component.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Id of the group to which this component belongs to.
        /// </summary>
        [Input("groupId")]
        public Input<string>? GroupId { get; set; }

        /// <summary>
        /// Name of the status page component.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Id of the status page to which this component belongs to.
        /// </summary>
        [Input("statusPageId")]
        public Input<string>? StatusPageId { get; set; }

        public PageComponentState()
        {
        }
        public static new PageComponentState Empty => new PageComponentState();
    }
}
