// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IrisDanded.Pulumi.Squadcast
{
    /// <summary>
    /// ## Example Usage
    /// </summary>
    [SquadcastResourceType("squadcast:index/workflowActionOrdering:WorkflowActionOrdering")]
    public partial class WorkflowActionOrdering : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The order of actions in the workflow
        /// </summary>
        [Output("actionOrders")]
        public Output<ImmutableArray<int>> ActionOrders { get; private set; } = null!;

        /// <summary>
        /// The ID of the workflow
        /// </summary>
        [Output("workflowId")]
        public Output<string> WorkflowId { get; private set; } = null!;


        /// <summary>
        /// Create a WorkflowActionOrdering resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public WorkflowActionOrdering(string name, WorkflowActionOrderingArgs args, CustomResourceOptions? options = null)
            : base("squadcast:index/workflowActionOrdering:WorkflowActionOrdering", name, args ?? new WorkflowActionOrderingArgs(), MakeResourceOptions(options, ""))
        {
        }

        private WorkflowActionOrdering(string name, Input<string> id, WorkflowActionOrderingState? state = null, CustomResourceOptions? options = null)
            : base("squadcast:index/workflowActionOrdering:WorkflowActionOrdering", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/IrisDande/pulumi-squadcast",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing WorkflowActionOrdering resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static WorkflowActionOrdering Get(string name, Input<string> id, WorkflowActionOrderingState? state = null, CustomResourceOptions? options = null)
        {
            return new WorkflowActionOrdering(name, id, state, options);
        }
    }

    public sealed class WorkflowActionOrderingArgs : global::Pulumi.ResourceArgs
    {
        [Input("actionOrders", required: true)]
        private InputList<int>? _actionOrders;

        /// <summary>
        /// The order of actions in the workflow
        /// </summary>
        public InputList<int> ActionOrders
        {
            get => _actionOrders ?? (_actionOrders = new InputList<int>());
            set => _actionOrders = value;
        }

        /// <summary>
        /// The ID of the workflow
        /// </summary>
        [Input("workflowId", required: true)]
        public Input<string> WorkflowId { get; set; } = null!;

        public WorkflowActionOrderingArgs()
        {
        }
        public static new WorkflowActionOrderingArgs Empty => new WorkflowActionOrderingArgs();
    }

    public sealed class WorkflowActionOrderingState : global::Pulumi.ResourceArgs
    {
        [Input("actionOrders")]
        private InputList<int>? _actionOrders;

        /// <summary>
        /// The order of actions in the workflow
        /// </summary>
        public InputList<int> ActionOrders
        {
            get => _actionOrders ?? (_actionOrders = new InputList<int>());
            set => _actionOrders = value;
        }

        /// <summary>
        /// The ID of the workflow
        /// </summary>
        [Input("workflowId")]
        public Input<string>? WorkflowId { get; set; }

        public WorkflowActionOrderingState()
        {
        }
        public static new WorkflowActionOrderingState Empty => new WorkflowActionOrderingState();
    }
}
