// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IrisDanded.Pulumi.Squadcast.Schedule.Rotation.Outputs
{

    [OutputType]
    public sealed class V2ParticipantGroupParticipant
    {
        /// <summary>
        /// Participant id.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Participant type (user, team, squad).
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private V2ParticipantGroupParticipant(
            string id,

            string type)
        {
            Id = id;
            Type = type;
        }
    }
}
