// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package squadcast

import (
	"context"
	"reflect"

	"errors"
	"github.com/IrisDande/pulumi-squadcast/sdk/go/squadcast/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The ordering of rules within a Ruleset dictates the sequence in which rules are evaluated for an alert source. These rules are evaluated sequentially, starting from the top.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/IrisDande/pulumi-squadcast/sdk/go/squadcast"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			exampleTeam, err := squadcast.LookupTeam(ctx, &squadcast.LookupTeamArgs{
//				Name: "Example Team",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			exampleUser, err := squadcast.LookupUser(ctx, &squadcast.LookupUserArgs{
//				Email: "john@example.com",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			exampleService, err := squadcast.LookupService(ctx, &squadcast.LookupServiceArgs{
//				Name:   "Example Service",
//				TeamId: exampleTeam.Id,
//			}, nil)
//			if err != nil {
//				return err
//			}
//			exampleGer, err := squadcast.NewGer(ctx, "exampleGer", &squadcast.GerArgs{
//				Description: pulumi.String("Example GER Description"),
//				TeamId:      pulumi.String(exampleTeam.Id),
//				EntityOwner: &squadcast.GerEntityOwnerArgs{
//					Id:   pulumi.String(exampleUser.Id),
//					Type: pulumi.String("user"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			exampleGerRuleset, err := squadcast.NewGerRuleset(ctx, "exampleGerRuleset", &squadcast.GerRulesetArgs{
//				GerId:       exampleGer.ID(),
//				AlertSource: pulumi.String("Prometheus"),
//				CatchAllAction: pulumi.StringMap{
//					"route_to": pulumi.String(exampleService.Id),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			_, err = squadcast.NewGerRulesetRule(ctx, "exampleGerRulesetRule1", &squadcast.GerRulesetRuleArgs{
//				GerId:       exampleGer.ID(),
//				AlertSource: exampleGerRuleset.AlertSource,
//				Expression:  pulumi.String("alertname == \"DeploymentReplicasNotUpdated\""),
//				Description: pulumi.String("Example GER Ruleset Rule"),
//				Action: pulumi.StringMap{
//					"route_to": pulumi.String(exampleService.Id),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			_, err = squadcast.NewGerRulesetRule(ctx, "exampleGerRulesetRule2", &squadcast.GerRulesetRuleArgs{
//				GerId:       exampleGer.ID(),
//				AlertSource: exampleGerRuleset.AlertSource,
//				Expression:  pulumi.String("component == \"kube-state-metrics\""),
//				Description: pulumi.String("Example GER Ruleset Rule"),
//				Action: pulumi.StringMap{
//					"route_to": pulumi.String(exampleService.Id),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			_, err = squadcast.NewGerRulesetRulesOrdering(ctx, "ruleOrdering", &squadcast.GerRulesetRulesOrderingArgs{
//				GerId:       pulumi.Any(squadcast_ger.Ger.Id),
//				AlertSource: pulumi.Any(squadcast_ger_ruleset.Ger_ruleset_1.Alert_source),
//				Orderings: pulumi.StringArray{
//					squadcast_ger_ruleset_rule.Ger_ruleset_rule_2.Id,
//					squadcast_ger_ruleset_rule.Ger_ruleset_rule_1.Id,
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// gerID:alertSourceName
//
// ```sh
// $ pulumi import squadcast:index/gerRulesetRulesOrdering:GerRulesetRulesOrdering example_ger_ruleset_rule_ordering_import "53:Grafana"
// ```
type GerRulesetRulesOrdering struct {
	pulumi.CustomResourceState

	// An alert source refers to the origin of an event (alert), such as a monitoring tool. These alert sources are associated with specific rules in GER, determining where events from each source should be routed. Find all alert sources supported on Squadcast [here](https://www.squadcast.com/integrations).
	AlertSource pulumi.StringOutput `pulumi:"alertSource"`
	// Shortname of the linked alert source.
	AlertSourceShortname pulumi.StringOutput `pulumi:"alertSourceShortname"`
	// Version of the linked alert source.
	AlertSourceVersion pulumi.StringOutput `pulumi:"alertSourceVersion"`
	// GER id.
	GerId pulumi.StringOutput `pulumi:"gerId"`
	// GER Ruleset Rule Ordering.
	Orderings pulumi.StringArrayOutput `pulumi:"orderings"`
}

// NewGerRulesetRulesOrdering registers a new resource with the given unique name, arguments, and options.
func NewGerRulesetRulesOrdering(ctx *pulumi.Context,
	name string, args *GerRulesetRulesOrderingArgs, opts ...pulumi.ResourceOption) (*GerRulesetRulesOrdering, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AlertSource == nil {
		return nil, errors.New("invalid value for required argument 'AlertSource'")
	}
	if args.GerId == nil {
		return nil, errors.New("invalid value for required argument 'GerId'")
	}
	if args.Orderings == nil {
		return nil, errors.New("invalid value for required argument 'Orderings'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource GerRulesetRulesOrdering
	err := ctx.RegisterResource("squadcast:index/gerRulesetRulesOrdering:GerRulesetRulesOrdering", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetGerRulesetRulesOrdering gets an existing GerRulesetRulesOrdering resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetGerRulesetRulesOrdering(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *GerRulesetRulesOrderingState, opts ...pulumi.ResourceOption) (*GerRulesetRulesOrdering, error) {
	var resource GerRulesetRulesOrdering
	err := ctx.ReadResource("squadcast:index/gerRulesetRulesOrdering:GerRulesetRulesOrdering", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering GerRulesetRulesOrdering resources.
type gerRulesetRulesOrderingState struct {
	// An alert source refers to the origin of an event (alert), such as a monitoring tool. These alert sources are associated with specific rules in GER, determining where events from each source should be routed. Find all alert sources supported on Squadcast [here](https://www.squadcast.com/integrations).
	AlertSource *string `pulumi:"alertSource"`
	// Shortname of the linked alert source.
	AlertSourceShortname *string `pulumi:"alertSourceShortname"`
	// Version of the linked alert source.
	AlertSourceVersion *string `pulumi:"alertSourceVersion"`
	// GER id.
	GerId *string `pulumi:"gerId"`
	// GER Ruleset Rule Ordering.
	Orderings []string `pulumi:"orderings"`
}

type GerRulesetRulesOrderingState struct {
	// An alert source refers to the origin of an event (alert), such as a monitoring tool. These alert sources are associated with specific rules in GER, determining where events from each source should be routed. Find all alert sources supported on Squadcast [here](https://www.squadcast.com/integrations).
	AlertSource pulumi.StringPtrInput
	// Shortname of the linked alert source.
	AlertSourceShortname pulumi.StringPtrInput
	// Version of the linked alert source.
	AlertSourceVersion pulumi.StringPtrInput
	// GER id.
	GerId pulumi.StringPtrInput
	// GER Ruleset Rule Ordering.
	Orderings pulumi.StringArrayInput
}

func (GerRulesetRulesOrderingState) ElementType() reflect.Type {
	return reflect.TypeOf((*gerRulesetRulesOrderingState)(nil)).Elem()
}

type gerRulesetRulesOrderingArgs struct {
	// An alert source refers to the origin of an event (alert), such as a monitoring tool. These alert sources are associated with specific rules in GER, determining where events from each source should be routed. Find all alert sources supported on Squadcast [here](https://www.squadcast.com/integrations).
	AlertSource string `pulumi:"alertSource"`
	// GER id.
	GerId string `pulumi:"gerId"`
	// GER Ruleset Rule Ordering.
	Orderings []string `pulumi:"orderings"`
}

// The set of arguments for constructing a GerRulesetRulesOrdering resource.
type GerRulesetRulesOrderingArgs struct {
	// An alert source refers to the origin of an event (alert), such as a monitoring tool. These alert sources are associated with specific rules in GER, determining where events from each source should be routed. Find all alert sources supported on Squadcast [here](https://www.squadcast.com/integrations).
	AlertSource pulumi.StringInput
	// GER id.
	GerId pulumi.StringInput
	// GER Ruleset Rule Ordering.
	Orderings pulumi.StringArrayInput
}

func (GerRulesetRulesOrderingArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*gerRulesetRulesOrderingArgs)(nil)).Elem()
}

type GerRulesetRulesOrderingInput interface {
	pulumi.Input

	ToGerRulesetRulesOrderingOutput() GerRulesetRulesOrderingOutput
	ToGerRulesetRulesOrderingOutputWithContext(ctx context.Context) GerRulesetRulesOrderingOutput
}

func (*GerRulesetRulesOrdering) ElementType() reflect.Type {
	return reflect.TypeOf((**GerRulesetRulesOrdering)(nil)).Elem()
}

func (i *GerRulesetRulesOrdering) ToGerRulesetRulesOrderingOutput() GerRulesetRulesOrderingOutput {
	return i.ToGerRulesetRulesOrderingOutputWithContext(context.Background())
}

func (i *GerRulesetRulesOrdering) ToGerRulesetRulesOrderingOutputWithContext(ctx context.Context) GerRulesetRulesOrderingOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GerRulesetRulesOrderingOutput)
}

// GerRulesetRulesOrderingArrayInput is an input type that accepts GerRulesetRulesOrderingArray and GerRulesetRulesOrderingArrayOutput values.
// You can construct a concrete instance of `GerRulesetRulesOrderingArrayInput` via:
//
//	GerRulesetRulesOrderingArray{ GerRulesetRulesOrderingArgs{...} }
type GerRulesetRulesOrderingArrayInput interface {
	pulumi.Input

	ToGerRulesetRulesOrderingArrayOutput() GerRulesetRulesOrderingArrayOutput
	ToGerRulesetRulesOrderingArrayOutputWithContext(context.Context) GerRulesetRulesOrderingArrayOutput
}

type GerRulesetRulesOrderingArray []GerRulesetRulesOrderingInput

func (GerRulesetRulesOrderingArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GerRulesetRulesOrdering)(nil)).Elem()
}

func (i GerRulesetRulesOrderingArray) ToGerRulesetRulesOrderingArrayOutput() GerRulesetRulesOrderingArrayOutput {
	return i.ToGerRulesetRulesOrderingArrayOutputWithContext(context.Background())
}

func (i GerRulesetRulesOrderingArray) ToGerRulesetRulesOrderingArrayOutputWithContext(ctx context.Context) GerRulesetRulesOrderingArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GerRulesetRulesOrderingArrayOutput)
}

// GerRulesetRulesOrderingMapInput is an input type that accepts GerRulesetRulesOrderingMap and GerRulesetRulesOrderingMapOutput values.
// You can construct a concrete instance of `GerRulesetRulesOrderingMapInput` via:
//
//	GerRulesetRulesOrderingMap{ "key": GerRulesetRulesOrderingArgs{...} }
type GerRulesetRulesOrderingMapInput interface {
	pulumi.Input

	ToGerRulesetRulesOrderingMapOutput() GerRulesetRulesOrderingMapOutput
	ToGerRulesetRulesOrderingMapOutputWithContext(context.Context) GerRulesetRulesOrderingMapOutput
}

type GerRulesetRulesOrderingMap map[string]GerRulesetRulesOrderingInput

func (GerRulesetRulesOrderingMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GerRulesetRulesOrdering)(nil)).Elem()
}

func (i GerRulesetRulesOrderingMap) ToGerRulesetRulesOrderingMapOutput() GerRulesetRulesOrderingMapOutput {
	return i.ToGerRulesetRulesOrderingMapOutputWithContext(context.Background())
}

func (i GerRulesetRulesOrderingMap) ToGerRulesetRulesOrderingMapOutputWithContext(ctx context.Context) GerRulesetRulesOrderingMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GerRulesetRulesOrderingMapOutput)
}

type GerRulesetRulesOrderingOutput struct{ *pulumi.OutputState }

func (GerRulesetRulesOrderingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GerRulesetRulesOrdering)(nil)).Elem()
}

func (o GerRulesetRulesOrderingOutput) ToGerRulesetRulesOrderingOutput() GerRulesetRulesOrderingOutput {
	return o
}

func (o GerRulesetRulesOrderingOutput) ToGerRulesetRulesOrderingOutputWithContext(ctx context.Context) GerRulesetRulesOrderingOutput {
	return o
}

// An alert source refers to the origin of an event (alert), such as a monitoring tool. These alert sources are associated with specific rules in GER, determining where events from each source should be routed. Find all alert sources supported on Squadcast [here](https://www.squadcast.com/integrations).
func (o GerRulesetRulesOrderingOutput) AlertSource() pulumi.StringOutput {
	return o.ApplyT(func(v *GerRulesetRulesOrdering) pulumi.StringOutput { return v.AlertSource }).(pulumi.StringOutput)
}

// Shortname of the linked alert source.
func (o GerRulesetRulesOrderingOutput) AlertSourceShortname() pulumi.StringOutput {
	return o.ApplyT(func(v *GerRulesetRulesOrdering) pulumi.StringOutput { return v.AlertSourceShortname }).(pulumi.StringOutput)
}

// Version of the linked alert source.
func (o GerRulesetRulesOrderingOutput) AlertSourceVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *GerRulesetRulesOrdering) pulumi.StringOutput { return v.AlertSourceVersion }).(pulumi.StringOutput)
}

// GER id.
func (o GerRulesetRulesOrderingOutput) GerId() pulumi.StringOutput {
	return o.ApplyT(func(v *GerRulesetRulesOrdering) pulumi.StringOutput { return v.GerId }).(pulumi.StringOutput)
}

// GER Ruleset Rule Ordering.
func (o GerRulesetRulesOrderingOutput) Orderings() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *GerRulesetRulesOrdering) pulumi.StringArrayOutput { return v.Orderings }).(pulumi.StringArrayOutput)
}

type GerRulesetRulesOrderingArrayOutput struct{ *pulumi.OutputState }

func (GerRulesetRulesOrderingArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GerRulesetRulesOrdering)(nil)).Elem()
}

func (o GerRulesetRulesOrderingArrayOutput) ToGerRulesetRulesOrderingArrayOutput() GerRulesetRulesOrderingArrayOutput {
	return o
}

func (o GerRulesetRulesOrderingArrayOutput) ToGerRulesetRulesOrderingArrayOutputWithContext(ctx context.Context) GerRulesetRulesOrderingArrayOutput {
	return o
}

func (o GerRulesetRulesOrderingArrayOutput) Index(i pulumi.IntInput) GerRulesetRulesOrderingOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *GerRulesetRulesOrdering {
		return vs[0].([]*GerRulesetRulesOrdering)[vs[1].(int)]
	}).(GerRulesetRulesOrderingOutput)
}

type GerRulesetRulesOrderingMapOutput struct{ *pulumi.OutputState }

func (GerRulesetRulesOrderingMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GerRulesetRulesOrdering)(nil)).Elem()
}

func (o GerRulesetRulesOrderingMapOutput) ToGerRulesetRulesOrderingMapOutput() GerRulesetRulesOrderingMapOutput {
	return o
}

func (o GerRulesetRulesOrderingMapOutput) ToGerRulesetRulesOrderingMapOutputWithContext(ctx context.Context) GerRulesetRulesOrderingMapOutput {
	return o
}

func (o GerRulesetRulesOrderingMapOutput) MapIndex(k pulumi.StringInput) GerRulesetRulesOrderingOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *GerRulesetRulesOrdering {
		return vs[0].(map[string]*GerRulesetRulesOrdering)[vs[1].(string)]
	}).(GerRulesetRulesOrderingOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GerRulesetRulesOrderingInput)(nil)).Elem(), &GerRulesetRulesOrdering{})
	pulumi.RegisterInputType(reflect.TypeOf((*GerRulesetRulesOrderingArrayInput)(nil)).Elem(), GerRulesetRulesOrderingArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GerRulesetRulesOrderingMapInput)(nil)).Elem(), GerRulesetRulesOrderingMap{})
	pulumi.RegisterOutputType(GerRulesetRulesOrderingOutput{})
	pulumi.RegisterOutputType(GerRulesetRulesOrderingArrayOutput{})
	pulumi.RegisterOutputType(GerRulesetRulesOrderingMapOutput{})
}
