// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IrisDanded.Pulumi.Squadcast.Tagging.Rule
{
    /// <summary>
    /// [Tagging](https://support.squadcast.com/docs/event-tagging) is a rule-based, auto-tagging system with which you can define customised tags based on incident payloads, that get automatically assigned to incidents when they are triggered.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Squadcast = IrisDanded.Pulumi.Squadcast;
    /// using Squadcast = Pulumi.Squadcast;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var exampleService = Squadcast.GetService.Invoke(new()
    ///     {
    ///         Name = "example service name",
    ///         TeamId = data.Squadcast_team.Example_team.Id,
    ///     });
    /// 
    ///     var exampleTaggingRule = new Squadcast.Tagging.Rule.V2("exampleTaggingRule", new()
    ///     {
    ///         ServiceId = exampleService.Apply(getServiceResult =&gt; getServiceResult.Id),
    ///         IsBasic = false,
    ///         Expression = "payload[\"event_id\"] == 40",
    ///         Tags = new[]
    ///         {
    ///             new Squadcast.Tagging.Rule.Inputs.V2TagArgs
    ///             {
    ///                 Key = "MyTag",
    ///                 Value = "foo",
    ///                 Color = "#ababab",
    ///             },
    ///             new Squadcast.Tagging.Rule.Inputs.V2TagArgs
    ///             {
    ///                 Key = "MyTag2",
    ///                 Value = "bar",
    ///                 Color = "#f0f0f0",
    ///             },
    ///         },
    ///     });
    /// 
    ///     var exampleBasicTaggingRule = new Squadcast.Tagging.Rule.V2("exampleBasicTaggingRule", new()
    ///     {
    ///         ServiceId = exampleService.Apply(getServiceResult =&gt; getServiceResult.Id),
    ///         IsBasic = true,
    ///         BasicExpressions = new[]
    ///         {
    ///             new Squadcast.Tagging.Rule.Inputs.V2BasicExpressionArgs
    ///             {
    ///                 Lhs = "payload[\"foo\"]",
    ///                 Op = "is",
    ///                 Rhs = "bar",
    ///             },
    ///         },
    ///         Tags = new[]
    ///         {
    ///             new Squadcast.Tagging.Rule.Inputs.V2TagArgs
    ///             {
    ///                 Key = "MyTag",
    ///                 Value = "foo",
    ///                 Color = "#ababab",
    ///             },
    ///         },
    ///     });
    /// 
    ///     // addTags must be set in expression when tags are not passed
    ///     var exampleTaggingRulesResourceWithouttags = new Squadcast.Tagging.Rule.V2("exampleTaggingRulesResourceWithouttags", new()
    ///     {
    ///         ServiceId = exampleService.Apply(getServiceResult =&gt; getServiceResult.Id),
    ///         IsBasic = false,
    ///         Expression = "addTag(\"EventType\", payload.details.event_type_key, \"#037916\")",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// serviceID:ruleID
    /// 
    /// ```sh
    /// $ pulumi import squadcast:tagging/rule/v2:V2 test 62d2fe23a57381088224d726:62da76c088f407f9ca756ca5
    /// ```
    /// </summary>
    [SquadcastResourceType("squadcast:tagging/rule/v2:V2")]
    public partial class V2 : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The basic expression which needs to be evaluated to be true for this rule to apply.
        /// </summary>
        [Output("basicExpressions")]
        public Output<ImmutableArray<Outputs.V2BasicExpression>> BasicExpressions { get; private set; } = null!;

        /// <summary>
        /// The expression which needs to be evaluated to be true for this rule to apply.
        /// </summary>
        [Output("expression")]
        public Output<string?> Expression { get; private set; } = null!;

        /// <summary>
        /// is_basic will be true when users use the drop down selectors which will have lhs, op &amp; rhs value, whereas it will be false when they use the advanced mode and it would have the expression for it's value
        /// </summary>
        [Output("isBasic")]
        public Output<bool> IsBasic { get; private set; } = null!;

        /// <summary>
        /// Service id.
        /// </summary>
        [Output("serviceId")]
        public Output<string> ServiceId { get; private set; } = null!;

        /// <summary>
        /// The tags supposed to be set for a given payload(incident), Expression must be set when tags are empty and must contain addTags parameters.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<Outputs.V2Tag>> Tags { get; private set; } = null!;


        /// <summary>
        /// Create a V2 resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public V2(string name, V2Args args, CustomResourceOptions? options = null)
            : base("squadcast:tagging/rule/v2:V2", name, args ?? new V2Args(), MakeResourceOptions(options, ""))
        {
        }

        private V2(string name, Input<string> id, V2State? state = null, CustomResourceOptions? options = null)
            : base("squadcast:tagging/rule/v2:V2", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/IrisDande/pulumi-squadcast",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing V2 resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static V2 Get(string name, Input<string> id, V2State? state = null, CustomResourceOptions? options = null)
        {
            return new V2(name, id, state, options);
        }
    }

    public sealed class V2Args : global::Pulumi.ResourceArgs
    {
        [Input("basicExpressions")]
        private InputList<Inputs.V2BasicExpressionArgs>? _basicExpressions;

        /// <summary>
        /// The basic expression which needs to be evaluated to be true for this rule to apply.
        /// </summary>
        public InputList<Inputs.V2BasicExpressionArgs> BasicExpressions
        {
            get => _basicExpressions ?? (_basicExpressions = new InputList<Inputs.V2BasicExpressionArgs>());
            set => _basicExpressions = value;
        }

        /// <summary>
        /// The expression which needs to be evaluated to be true for this rule to apply.
        /// </summary>
        [Input("expression")]
        public Input<string>? Expression { get; set; }

        /// <summary>
        /// is_basic will be true when users use the drop down selectors which will have lhs, op &amp; rhs value, whereas it will be false when they use the advanced mode and it would have the expression for it's value
        /// </summary>
        [Input("isBasic", required: true)]
        public Input<bool> IsBasic { get; set; } = null!;

        /// <summary>
        /// Service id.
        /// </summary>
        [Input("serviceId", required: true)]
        public Input<string> ServiceId { get; set; } = null!;

        [Input("tags")]
        private InputList<Inputs.V2TagArgs>? _tags;

        /// <summary>
        /// The tags supposed to be set for a given payload(incident), Expression must be set when tags are empty and must contain addTags parameters.
        /// </summary>
        public InputList<Inputs.V2TagArgs> Tags
        {
            get => _tags ?? (_tags = new InputList<Inputs.V2TagArgs>());
            set => _tags = value;
        }

        public V2Args()
        {
        }
        public static new V2Args Empty => new V2Args();
    }

    public sealed class V2State : global::Pulumi.ResourceArgs
    {
        [Input("basicExpressions")]
        private InputList<Inputs.V2BasicExpressionGetArgs>? _basicExpressions;

        /// <summary>
        /// The basic expression which needs to be evaluated to be true for this rule to apply.
        /// </summary>
        public InputList<Inputs.V2BasicExpressionGetArgs> BasicExpressions
        {
            get => _basicExpressions ?? (_basicExpressions = new InputList<Inputs.V2BasicExpressionGetArgs>());
            set => _basicExpressions = value;
        }

        /// <summary>
        /// The expression which needs to be evaluated to be true for this rule to apply.
        /// </summary>
        [Input("expression")]
        public Input<string>? Expression { get; set; }

        /// <summary>
        /// is_basic will be true when users use the drop down selectors which will have lhs, op &amp; rhs value, whereas it will be false when they use the advanced mode and it would have the expression for it's value
        /// </summary>
        [Input("isBasic")]
        public Input<bool>? IsBasic { get; set; }

        /// <summary>
        /// Service id.
        /// </summary>
        [Input("serviceId")]
        public Input<string>? ServiceId { get; set; }

        [Input("tags")]
        private InputList<Inputs.V2TagGetArgs>? _tags;

        /// <summary>
        /// The tags supposed to be set for a given payload(incident), Expression must be set when tags are empty and must contain addTags parameters.
        /// </summary>
        public InputList<Inputs.V2TagGetArgs> Tags
        {
            get => _tags ?? (_tags = new InputList<Inputs.V2TagGetArgs>());
            set => _tags = value;
        }

        public V2State()
        {
        }
        public static new V2State Empty => new V2State();
    }
}
