// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IrisDanded.Pulumi.Squadcast.Inputs
{

    public sealed class SuppressionRuleV2BasicExpressionGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// left hand side dropdown value
        /// </summary>
        [Input("lhs", required: true)]
        public Input<string> Lhs { get; set; } = null!;

        /// <summary>
        /// operator (is, is*not, matches, not*contains)
        /// </summary>
        [Input("op", required: true)]
        public Input<string> Op { get; set; } = null!;

        /// <summary>
        /// right hand side value
        /// </summary>
        [Input("rhs", required: true)]
        public Input<string> Rhs { get; set; } = null!;

        public SuppressionRuleV2BasicExpressionGetArgs()
        {
        }
        public static new SuppressionRuleV2BasicExpressionGetArgs Empty => new SuppressionRuleV2BasicExpressionGetArgs();
    }
}
