// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IrisDanded.Pulumi.Squadcast.Inputs
{

    public sealed class WorkflowFiltersGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Condition to be applied on the filters (and / or)
        /// </summary>
        [Input("condition", required: true)]
        public Input<string> Condition { get; set; } = null!;

        [Input("filters")]
        private InputList<Inputs.WorkflowFiltersFilterGetArgs>? _filters;
        public InputList<Inputs.WorkflowFiltersFilterGetArgs> Filters
        {
            get => _filters ?? (_filters = new InputList<Inputs.WorkflowFiltersFilterGetArgs>());
            set => _filters = value;
        }

        public WorkflowFiltersGetArgs()
        {
        }
        public static new WorkflowFiltersGetArgs Empty => new WorkflowFiltersGetArgs();
    }
}
